### ISSUE TITLE
Add a filter result listing tile

### ISSUE THREAD

**Issue by petschki** [collective/collective.collectionfilter#40]
In order to make it possible OOTB to create tile (mosaic) pages with filter tiles updating a result listing it is necessary to add some kind of "filter result listing tile" ... I tried it with `Existing Content` tile from `plone.app.standardtiles` but there is no matching target selector in the tile template because it only places the nodes within the `content-core` macro of the collections default_view... (NOTE: `summary_view` doesn't even have a defined `content-core` macro ... see https://github.com/plone/plone.app.contenttypes/pull/515)

**Comment by djay** [comment]
@petschki isn't that what the collection tile is supposed to be?

**Comment by petschki** [comment]
I have to check that ...

**Comment by djay** [comment]
@petschki  The idea was that in a world with just mosaic you no longer need collections at all. Collections become a page that has a content listing tile on it. The content listing tile replaces both a folder listing and the collection uses cases.

So to make collectionfilter work in this case you would need to

- get rid of the target_collection field (unless the filter is on a site_layout? even then it doesn't make much sense. In fact the target_collection doesn't make a lot of sense anyway in the portlet case because if you don't have a collection in your ansestors then collection filter redirects you to the target collection which is not expected)
- work out how to interact with the tile on the page to get the base search params... thats not easy because there is not api for accessing transient tile settings of another tile on the same page I believe.
- handle the case where you might have more than one content filter tile on the same page?

**Comment by petschki** [comment]
this is outdated and solved by the `contentlisting-tile` with `use query from context` enabled on a Collection context ...

**Comment by petschki** [comment]
note: you can define a page-wide unique CSS class for the contentlisting tile, which you then use as `content selector` for the filter tiles ... so AJAX is working smoothly
